import Head from "next/head";
import Header from "../components/Header";
import Mid from "../components/Mid";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="font-main ">
      <Head>
        <title>Cloud Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex">
        <Sidebar />
        <Mid />
      </main>
    </div>
  );
}
